# Generated by Django 3.0 on 2019-12-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('location', 'rating')},
        ),
    ]
